### ISSUE TITLE
Update Data Sent to Statistics Collection API

### ISSUE THREAD

**Issue by t1msammut** [itemir/thundersec#10]
The plug-in should send the following data at the specified events to the statistics collection API:
                                                                                
* **Timed Periodic Events:** These are general stats sent once every X hours in order to determine which plug-in functionality is useful. NOTE: The same email opened multiple times can be counted multiple times below.
 * The number of emails checked during the last interval                        
 * The number of emails that had one or more DNSBL BAD results and were NOT whitelisted 
 * The number of emails that had one or more DNSBL BAD results but were whitelisted                                   
 * The number of emails that had a DKIM failure and were NOT whitelisted  
 * The number of emails that had a DKIM failure but were whitelisted                                                              
 * The number of emails that had a SPF failure and were NOT whitelisted
 * The number of emails that had a SPF failure but were whitelisted                                                                   
 * The version of the Thundersec plug-in being used                             
                                                                                
* **DNSBL Block Events:** These are sent when a DNSBL indicates a low reputation for an IP address used to transfer the mail in order for us to appropriately choose DNSBLs used in the plug-in.
 * IP Address triggering the event                                              
 * DNSBL service triggering the event                                           
 * Code returned from the DNSBL service                                         
 * The version of the Thundersec plug-in being used                             
                                                                                
* **DNSBL Whitelist Events:** These are sent when a user overrides the DNSBL to indicate that an IP+sender+DNSBL is OK despite the DNSBL result. These is used to help us determine the accuracy of the DNSBLs used by the plug-in.
 * IP Address triggering the event                                              
 * DNSBL service triggering the event                                           
 * Code returned from the DNSBL service
 * The SHA-256 hash representing the email address being whitelisted                                         
 * The version of the Thundersec plug-in being used                             
                                                                                
At this time, and this may change, I don't believe we have a use for capturing specific DKIM or SPF failure information via the API. The general/periodic statistics sent via the API should give us an indication of their usefulness.

**Comment by itemir** [comment]
What happens to whitelisted failures, should they increment the counters for number of failures?

**Comment by itemir** [comment]
We also need to clarify the situation with DKIM and SPF white-listing events. I think these should also be included in statistics, legitimate cases generate DKIM and SPF violations and having an insight into those would be useful.

**Comment by t1msammut** [comment]
> What happens to whitelisted failures, should they increment the counters for number of failures?

Yeah, we should capture those. Updated the list at the top to include whitelisted failures and be more specific on non-whitelisted failures.

 * The number of emails that had one or more DNSBL BAD results and were NOT whitelisted 
 * The number of emails that had one or more DNSBL BAD results but were whitelisted                                   
 * The number of emails that had a DKIM failure and were NOT whitelisted  
 * The number of emails that had a DKIM failure but were whitelisted                                                              
 * The number of emails that had a SPF failure and were NOT whitelisted
 * The number of emails that had a SPF failure but were whitelisted

**Comment by t1msammut** [comment]
> We also need to clarify the situation with DKIM and SPF white-listing events. I think these should also be included in statistics, legitimate cases generate DKIM and SPF violations and having an insight into those would be useful.

Discussed offline and we've agreed to hold-off on collecting specific details about DKIM and SPF failures and whitelist events.

The spec above is current (as of now ;).

**Comment by itemir** [comment]
This is implemented as follows.

An API call is made every hour to send the following data:

periodStart: Start of the data collection period (in epoch)
periodEnd: End of the data collection period (in epoch)
inspectTotal: Total number of inspected messages in the given period (same message can count multiple times)
dnsblLookup: Number of total DNSBL lookups in the given period. This will almost always be higher than inspectTotal as multiple lookups are done for each message.
dnsblViolation: Number of DNSBL violations in the given period (including white-listed ones)
dnsblWhitelist: Number of white-listed entries in dnsblVilolation. If an IP is in DNSBL but white-listed, that lookup will increment both dnsblViolation and dnsblWhitelist.
spfViolation: Number of SPF violations in the given period (including white-listed ones)
spfWhitelist: Number of white-listed entries in spfVilolation. If the violation iswhite-listed, that will increment both spfViolation and spfWhitelist.
dkimViolation: Number of DKIM violations in the given period (including white-listed ones)
dkimWhitelist: Number of white-listed entries in dkimVilolation. If the violation iswhite-listed, that will increment both dkimViolation and dkimWhitelist.
