### ISSUE TITLE
DKIM failures with neutral status

### ISSUE THREAD

**Issue by itemir** [itemir/thundersec#14]
I am noticing a fair bit of legitimate e-mails being marked with DKIM failures. A typical scenario is mailing list distributions but it is certainly more common than that. Some of the relevant headers lines are as follows from two different e-mails.

dkim=neutral (body hash did not verify) 
dkim=neutral (message not signed)

We need confirm if it is right to treat dkim=neutral as a violation (which is what the current implementation is doing).

**Comment by t1msammut** [comment]
After rereading the RFC, dkim=neutral should result the messaging being treated as unsigned, and therefore not a failure.

**Comment by t1msammut** [comment]
Closed by https://github.com/itemir/thundersec/commit/c8fef26fbe02b63d6e5e106363f405c008093a7f
