### ISSUE TITLE
Thundersec prevents shutting down

### ISSUE THREAD

**Issue by ValdikSS** [itemir/thundersec#18]
Thundersec does not allow Thunderbird 38.1 to correctly shut down while activated. Worked fine with previous Thunderbird versions.

**Comment by FTWMike** [comment]
This issue actually started under 38.0.1 and has persisted now into 38.1.
Crash reports:
38.0.1 ID: e87fc7e1-ac40-4620-878b-79bc52150613
38.1 ID: a3176dc0-b5de-4f44-8a98-259922150711

**Comment by itemir** [comment]
Looking into it.

On 7/11/15 1:46 PM, FTWMike wrote:
>
> This issue actually started under 38.0.1 and has persisted now into 38.1.
> Crash reports:
> 38.0.1 ID: e87fc7e1-ac40-4620-878b-79bc52150613
> 38.1 ID: a3176dc0-b5de-4f44-8a98-259922150711
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/itemir/thundersec/issues/18#issuecomment-120660783>.
>

-- 
Ilker Temir
<https://twitter.com/IlkerTemir> <https://www.linkedin.com/in/ilkertemir>

**Comment by itemir** [comment]
I just committed a fix. Please test and let me know if you see any more issues.

**Comment by ValdikSS** [comment]
Works fine. Thank you!

**Comment by FTWMike** [comment]
Agreed, Thank you for the quick response and fix.
