### ISSUE TITLE
Request: Display FPS/DKIM pass/fail/missing info in toolbar or header

### ISSUE THREAD

**Issue by Skrapion** [itemir/thundersec#19]
I'd love to be able to get a feel for how many of my contacts send valid SPF/DKIM messages. Since Thundersec already does most of this work, it would be cool if it displayed that info somewhere.

**Comment by itemir** [comment]
Thanks for the suggestion Rick. We don't currently hold state on a per sender/contact basis so aggregating this data for different contacts would constitute a fairly significant change. I will keep it in the list of things to be considered.

**Comment by Skrapion** [comment]
Oh, sorry, I see how the body of my message was misleading. I didn't mean for it to sound like I wanted aggregate data. All I really want is an icon in the header saying whether the DKIM/SPF data in each message is valid/invalid/not present. (Although I suppose displaying "valid" is unnecessary.)

**Comment by itemir** [comment]
Oh I see. We already display when the SPF/DKIM check fails. Do you want to see when they succeed too?

**Comment by Skrapion** [comment]
I'd like to see when they're missing.

**Comment by shanet** [comment]
+1 for this. I installed the extension and spent about 15 minutes wondering why it appeared it wasn't working. Turns out that all of the messages I checked either had good signatures or no signature at all. Having the option to display a green bar when everything checks out and/or a grey bar when something is missing would be helpful from both satisfying my curiosity and from a UX perspective.

**Comment by itemir** [comment]
I will address this in the next (1.2) release.

**Comment by sfringer** [comment]
I was in the same situation as @shanet. Looking forward to the addition in 1.2.
Definitely appreciate your effort on this extension.

**Comment by itemir** [comment]
Year end shutdown is approaching. I am hoping to have some time to work on this over the Christmas break, stay tuned.

**Comment by itemir** [comment]
Just committed code for this. This is a configurable option (enabled by default) that can be disabled. Please test and let me know if you see any issues. 

Note that this change went in together with SURBL support, so the change is fairly significant.

**Comment by shanet** [comment]
Working great here. Thanks!

**Comment by Skrapion** [comment]
Just trying this now with 2.0.1, but unless I'm missing something, it still appears that it's not possible to differentiate between an email that passed the security violations and an email that has no security features at all.

I can send an email from a domain with an SPF record and one without, and in both cases it just gives me a grey bar that says "No DNSBL, SURBL, SPF, or DKIM violations."

What I want it to say is "Valid SPF information", "Valid DKIM signature and SPF information", or "Valid DKIM signature" if that information is present and valid.
