### ISSUE TITLE
Possible to mark messages as junk?

### ISSUE THREAD

**Issue by ThePianoGuy** [itemir/thundersec#20]
How can I automatically mark messages as junk, if there is a DNSBL violation?

I see "DNSBL Violation.  Please check Details for more information." if I open the message.  However, I don't really need to open the message because I can tell by the sender/subject that a message is spam.  I'm trying to figure out how to configure Thundersec so that spam is routed to my Junk folder, before I see it.

Thanks!

**Comment by itemir** [comment]
Hi PianoGuy,

Unfortunately this is not possible without a significant change in our approach. We only analyze a message when you actually view or open it, that triggers the event to do an SPF/DNSBL/DKIM check. Doing those checks proactively for all messages on the client side would add quite a bit overhead to your e-mail client.

**Comment by ThePianoGuy** [comment]
Thank you for the reply.  Maybe it's time for me to learn how to write Thunderbird extensions!

**Comment by itemir** [comment]
I have just given this a try in maybe a slightly different way than we discussed before. 

There is now a button to "Mark as Junk" when a message fails DNSBL/DKIM or SPF checks. This is a manual step.

In addition to the manual process, there is now also an advanced setting in preferences (disabled by default) that allows you to automatically mark messages as Junk if they fail DNSBL, DKIM or SPF checks. 

For both scenarios, you still need to open the message as that is the trigger for message inspection. 

I have uploaded 1.1 code to GitHub, please try and let me know how it works. Some testing will be appreciated as this includes some tricky changes.
