### ISSUE TITLE
FossaMail support

### ISSUE THREAD

**Issue by itemir** [itemir/thundersec#21]
Request from Mozilla Add-on Reviews:

_Can you please add FossaMail support? Its a Thunderbird fork from the Pale Moon develeoper and use the Pale Moon backend._

**Comment by beerisgood** [comment]
Sorry for the long time for not answer here.
Beside the problem that it looks the addon didn't work i found a problem which remove the statusbar entry if thundersec is enabled.

**Comment by beerisgood** [comment]
Any plans to support Fossa Mail?

**Comment by itemir** [comment]
Potentially yes but I am on a Mac and I can't try Fossa Mail on it. I will try to see if it is an easy issue by coordinating with Tim but if it turns out to be a complex port, I am afraid it won't be soon.

**Comment by beerisgood** [comment]
*push*

**Comment by itemir** [comment]
Sorry @beerisgood, both Tim and I are buried with our startup. I am afraid, we won't be able to work on this. 

I am closing it. If you are interested in giving it a try, please do so, more than happy to evaluate pull requests.

**Comment by beerisgood** [comment]
Too bad.

**Comment by beerisgood** [comment]
The addon works with the current version of FossaMail (v27) !

**Comment by itemir** [comment]
Awesome! Very glad to hear it. Thanks for following up and letting us know.
