### ISSUE TITLE
Please add URIBL and SURBL support

### ISSUE THREAD

**Issue by wadrian** [itemir/thundersec#22]
It would be great if you can support uribl and surbl services.
Both helps much to block spam independent from the mail header.

http://uribl.com/about.shtml
http://www.surbl.org/

from surbl website:
„SURBLs are lists of web sites that have appeared in unsolicited messages. Unlike most lists, SURBLs are not lists of message senders.“

from uribl website:
„URIBL lists domains that appear in spam, NOT where they were sent from. Our lists are intended to be used with antispam software to help TAG emails as spam.“

**Comment by itemir** [comment]
I just committed new code to github that introduces support for SURBLs. It currently supports multi.uribl.com and multi.surbl.org. You can also define custom SURBL services.

This is a fairly significant change. Please test it and let me know if you see any issues. 

And if you know other reliable SURBL services to include into prepopulated list of available services, let me know.

**Comment by wadrian** [comment]
I installed the beta a few days ago. Your implemention of surbl works fine.
Thanks a lot for realisation.
