### ISSUE TITLE
SURBL lookups may get stuck in specific messages

### ISSUE THREAD

**Issue by itemir** [itemir/thundersec#24]
@ValdikSS reports that mails from habrahabr.ru causes SURBL DNS lookups to get stuck.

**Comment by itemir** [comment]
If it is not sensitive, can you send the full message body (with headers) of a message that is causing problems.

**Comment by ValdikSS** [comment]
https://gist.githubusercontent.com/ValdikSS/b7f6415c210c879750b4/raw/bde11d91de5edf91a8e82fa3ca5dbcd32b0e0be9/gistfile1.txt
Please download it and I'll delete it.

**Comment by itemir** [comment]
Got it.

**Comment by sfringer** [comment]
I am also noting stuck DNS lookups with SURBL services enabled.
Messages are from the SANS Advisory list.

**Comment by itemir** [comment]
Just committed a fix which I think will fix this issue. Please get the latest version (2.0.1) from GitHub and see if works.

**Comment by ValdikSS** [comment]
Seems to work fine, thanks!
