### ISSUE TITLE
Add DKIM support

### ISSUE THREAD

**Issue by itemir** [itemir/thundersec#7]
Inspect e-mail headers for DKIM failures.

Sample header:

Authentication-Results: m1.example.com; dkim=fail
	reason="verification failed; insecure key"
	header.d=gmail.com header.i=@gmail.com header.b=ExjsdAFr;
	dkim-adsp=none (insecure policy); dkim-atps=neutral

**Comment by t1msammut** [comment]
When parsing the Authentication-Results header for DKIM status we should interpret the dkim= element as follows, according to https://tools.ietf.org/html/rfc7001#section-2.6.1:

OK status (no indication by the plug-in): none, pass
BAD status (to be indicated by the plug-in): fail, policy, neutral, temperror, permerror

Additionally, if there is no indication of dkim status in the Authentication-Results header, we should assume OK.

**Comment by t1msammut** [comment]
It looks as though the Authentication-Results header is the standard way to convey DKIM status in an email. Although the RFC says MAY, I don't see another header being used for this.

http://www.ietf.org/rfc/rfc6376.txt
6.2.  Communicate Verification Results
   Verifiers wishing to communicate the results of verification to other
   parts of the mail system may do so in whatever manner they see fit.
   For example, implementations might choose to add an email header
   field to the message before passing it on.  Any such header field
   SHOULD be inserted before any existing DKIM-Signature or preexisting
   authentication status header fields in the header field block.  The
   Authentication-Results: header field ([RFC5451]) MAY be used for this
   purpose.

**Comment by itemir** [comment]
Ok cool. Current implementation is consistent with it.

**Comment by t1msammut** [comment]
I have found a series of emails that contain Authentication-Results headers like this:

Authentication-Results: RELAY; dkim=neutral (message not signed) header.i=none

From my reading of the RFC, this is not correct...

(Note to Tim: TC)
