### ISSUE TITLE
Add SPF support

### ISSUE THREAD

**Issue by itemir** [itemir/thundersec#8]
Inspect e-mail headers for SPF failures.

Sample header:

Received-SPF: softfail (google.com: domain of transitioning info@example.com does not designate A.B.C.D as permitted sender) client-ip=A.B.C.D;

**Comment by t1msammut** [comment]
For the record :) we should be using Received-SPF, as you correct state above, and not the seemingly inconsistently implemented for SPF Authentication-Results header.

**Comment by t1msammut** [comment]
For SPF status determination via the Received-SPF header, we should use the following statuses to determine OK or BAD status.

OK: none, neutral and pass
BAD: fail, softfail, policy, temperror, permerror

Additionally, if no Received-SPF header is present we should not indicate a security issue in the plug-in.

For references, this was derived using the following RFCs:
https://tools.ietf.org/html/rfc4408#section-2.5
https://tools.ietf.org/html/rfc7001#section-2.6.2

**Comment by itemir** [comment]
This has been addressed with the latest commit.
