### ISSUE TITLE
Consider adding more details to the API call for version check

### ISSUE THREAD

**Issue by itemir** [itemir/thundersec#9]
Plugin performs a check every day for newer versions of itself via an API call to the cloud. This is what comes back:

{"version": "0.1", "description": "Initial version"}

This information can include additional details such as hash of the latest version's binary, direct download URL and release date.

**Comment by t1msammut** [comment]
Information URL or Release Notes URL or Announcement URL should be considered too.

**Comment by itemir** [comment]
Agreed.

**Comment by itemir** [comment]
Partially addressed this for the v1.0 release. Currently, the API returns the following fields:

{"url": "https://github.com/itemir/thundersec", "checksum": null, "version": "1.0", "description": "Initial public release", "released": "2015-02-15"}

Only version, description and URL are used on the client side. Leveraging URL is a new addition for v1.0 release. It is used in window.open if the user wants to download the new version (as opposed to HOME_URL as previously done).
